# Taken from SR7 Repo --> disabled rn as still figuring out codebuild 
# name: AWS CodeBuild Dev Build
# on: push
# permissions:
#   id-token: write # This is required for requesting the JWT
#   contents: read  # This is required for actions/checkout
#
# jobs:
#   LatestCodeBuildRunner:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@v2
#       with:
#         role-to-assume: arn:aws:iam::048391073693:role/GithubActionCodebuildRole
#         role-session-name: github_oidc_push
#         aws-region: ap-southeast-2
#
#     - name: Run CodeBuild
#       uses: aws-actions/aws-codebuild-run-build@v1
#       with:
#         project-name: embedded-highlevel-latest-arm64
