version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-southeast-2
    S3_BUCKET: sr8-embd-dev-env-ap-southeast-2
    QNX_SDP: qnx/qnx-sdp.tar.gz
    RTI: rti/rti_connext.tar

phases:
  pre_build:
    commands:
      - mkdir -p artifacts
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URL
      - GIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - aws s3 cp "s3://${S3_BUCKET}/${QNX_SDP}" "artifacts/qnx800.tar.gz"
      - aws s3 cp "s3://${S3_BUCKET}/${RTI}" "artifacts/rti_connext.tar"
  build:
    commands:
      # Build for ARM64 (macOS Apple Silicon)
      # - docker build --platform linux/arm64 --build-arg USER_NAME=developer --build-arg GROUP_NAME=developer --build-arg USER_ID=1000 --build-arg GROUP_ID=1000 --build-arg QNX_SDP_VERSION=8.0 -t $IMAGE_REPO_NAME:macos-arm64-$GIT_HASH .
      # - docker build --platform linux/arm64 --build-arg USER_NAME=developer --build-arg GROUP_NAME=developer --build-arg USER_ID=1000 --build-arg GROUP_ID=1000 --build-arg QNX_SDP_VERSION=8.0 -t $IMAGE_REPO_NAME:macos-arm64-latest .

      # Build for AMD64 (Windows/Intel)
      - docker build --platform linux/amd64 -f docker/Dockerfile --build-arg USER_NAME=developer --build-arg GROUP_NAME=developer --build-arg USER_ID=1000 --build-arg GROUP_ID=1000 --build-arg QNX_SDP_VERSION=8.0 -t $IMAGE_REPO_NAME:windows-amd64-$GIT_HASH .
      - docker build --platform linux/amd64 -f docker/Dockerfile --build-arg USER_NAME=developer --build-arg GROUP_NAME=developer --build-arg USER_ID=1000 --build-arg GROUP_ID=1000 --build-arg QNX_SDP_VERSION=8.0 -t $IMAGE_REPO_NAME:windows-amd64-latest .

      # Tag for ECR
      - docker tag $IMAGE_REPO_NAME:macos-arm64-$GIT_HASH $ECR_URL/$IMAGE_REPO_NAME:macos-arm64-$GIT_HASH
      - docker tag $IMAGE_REPO_NAME:macos-arm64-latest $ECR_URL/$IMAGE_REPO_NAME:macos-arm64-latest
      - docker tag $IMAGE_REPO_NAME:windows-amd64-$GIT_HASH $ECR_URL/$IMAGE_REPO_NAME:windows-amd64-$GIT_HASH
      - docker tag $IMAGE_REPO_NAME:windows-amd64-latest $ECR_URL/$IMAGE_REPO_NAME:windows-amd64-latest
  post_build:
    commands:
      - echo Pushing docker images...
      - docker push $ECR_URL/$IMAGE_REPO_NAME:macos-arm64-$GIT_HASH
      - docker push $ECR_URL/$IMAGE_REPO_NAME:macos-arm64-latest
      - docker push $ECR_URL/$IMAGE_REPO_NAME:windows-amd64-$GIT_HASH
      - docker push $ECR_URL/$IMAGE_REPO_NAME:windows-amd64-latest
