# This workflow is no longer needed - CodeStar in CDK detects pushes automatically; here for reference only
# name: AWS CodePipeline Observer
# on: push

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   MonitorBuild:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           # CHANGE TO PROD VALUE ONCE PUSHING TO PROD!!
#           role-to-assume: arn:aws:iam::124921357472:role/GithubActionCodebuildRole
#           role-session-name: github_oidc_push
#           aws-region: ap-southeast-2

#       - name: Check Pipeline Status
#         run: |
#           echo "Push on main detected"
#           # Get the latest pipeline execution
#           EXECUTION_ID=$(aws codepipeline list-pipeline-executions \
#             --pipeline-name EMBD-High-Level-Infra-Pipeline \
#             --max-items 1 \
#             --query 'pipelineExecutionSummaries[0].pipelineExecutionId' \
#             --output text)

#           STATUS=$(aws codepipeline get-pipeline-execution \
#             --pipeline-name EMBD-High-Level-Infra-Pipeline \
#             --pipeline-execution-id $EXECUTION_ID \
#             --query 'pipelineExecution.status' \
#             --output text)

#           echo "Pipeline: $EXECUTION_ID"
#           echo "Status: $STATUS"
#           echo "Cloudwatch Logs: https://ap-southeast-2.console.aws.amazon.com/codesuite/codepipeline/pipelines/EMBD-High-Level-Infra-Pipeline/view"
